### ISSUE TITLE
Add a better way of setting up Data Path as visibility driver for an attribute

### ISSUE THREAD

**Issue by nextr3d** [nextr3d/Character-UI#4]
Current implementation has the intended functionality of hiding attribute when the value from some **Data Path** doesn't equal to the set value.

This works nice but users get confused what **Data Path** actually is even though they might have use it when setting up drivers.

### Solution

Make the UI look similar to the drivers UI so users just select an object, world, etc and copy the **Data Path**. It should look something like this

![attr](https://user-images.githubusercontent.com/60177837/117959513-6337f580-b31c-11eb-8ddc-545ac8347abc.png)
--- 

User will just right click a *button* and Hit **Shift+Control+C** or Click **Copy Data Path**, select the correct type, select one of the items belonging to the selected type and paste in the copied **Data Path** .

**Comment by JanVavrinek** [comment]
Hey, I noticed you haven't touched this issue in quite some time so I thought I might try to make it myself. I already managed to create the enum for the prop type.

So if it's okay with you I'd like to tackle this issue.

**Comment by nextr3d** [comment]
Hi, yeah sure. This feature wasn't the top priority for me so it's nice that you decided to help me out. 

I have no idea how contributing works so if you need any permissions to create a new branch or anything else let me know! Or maybe you have to fork the repo and than I can merge it? Like I said, no idea 😅 but we'll figure it out!

**Comment by JanVavrinek** [comment]
Yes, I have to fork your repository and after I'm done I will create a pull request so you can merge my changes upstream if you like them. :)

I already forked it and you can checkout the branch called  [*data_path_improvement*](https://github.com/JanVavrinek/Character-UI/tree/data_path_improvement)

For now I only added the enum for selecting the block's type and the actual selector for the prop. It's not working at all but I just wanted to show it to you how this works.
